from pynput.keyboard import Key
from pynput.mouse import Button
import enum

class Binds(enum.Enum):
	# val, needs_translation, on_keyboard
	a = ('a', False, True)
	b = ('b', False, True)
	c = ('c', False, True)
	d = ('d', False, True)
	e = ('e', False, True)
	f = ('f', False, True)
	g = ('g', False, True)
	h = ('h', False, True)
	i = ('i', False, True)
	j = ('j', False, True)
	k = ('k', False, True)
	l = ('l', False, True)
	m = ('m', False, True)
	n = ('n', False, True)
	o = ('o', False, True)
	p = ('p', False, True)
	q = ('q', False, True)
	r = ('r', False, True)
	s = ('s', False, True)
	t = ('t', False, True)
	u = ('u', False, True)
	v = ('v', False, True)
	w = ('w', False, True)
	x = ('x', False, True)
	y = ('y', False, True)
	z = ('z', False, True)
	ZERO = ('0', False, True)
	ONE = ('1', False, True)
	TWO = ('2', False, True)
	THREE = ('3', False, True)
	FOUR = ('4', False, True)
	FIVE = ('5', False, True)
	SIX = ('6', False, True)
	SEVEN = ('7', False, True)
	EIGHT = ('8', False, True)
	NINE = ('9', False, True)
	Comma = (',', False, True)
	Period = ('.', False, True)
	Semicolon = (';', False, True)
	Minus = ('-', False, True)
	Equal = ('=', False, True)
	LBrack = ('[', False, True)
	RBrack = (']', False, True)
	FSlash = ('\\', False, True)

	LMB = (Button.left, True, False)
	RMB = (Button.right, True, False)
	MB4 = (Button.four, True, False)
	MB5 = (Button.five, True, False)

	LAlt = (Key.alt_l, True, True)
	CapsLock = (Key.caps_lock, True, True)
	LCtrl = (Key.ctrl_l, True, True)
	LShift = (Key.shift_l, True, True)
	Space = (Key.space, True, True)
	Tab = (Key.tab, True, True)
	F1 = (Key.f1, True, True)
	F2 = (Key.f2, True, True)
	F3 = (Key.f3, True, True)
	F4 = (Key.f4, True, True)
	F5 = (Key.f5, True, True)
	F6 = (Key.f6, True, True)

	
