from pynput.keyboard import Key
from pynput.mouse import Button
import enum

class Binds(enum.Enum):
	# val, needs_translation, on_keyboard
	a = ('a', False, True, "A")
	b = ('b', False, True, "B")
	c = ('c', False, True, "C")
	d = ('d', False, True, "D")
	e = ('e', False, True, "E")
	f = ('f', False, True, "F")
	g = ('g', False, True, "G")
	h = ('h', False, True, "H")
	i = ('i', False, True, "I")
	j = ('j', False, True, "J")
	k = ('k', False, True, "K")
	l = ('l', False, True, "L")
	m = ('m', False, True, "M")
	n = ('n', False, True, "N")
	o = ('o', False, True, "O")
	p = ('p', False, True, "P")
	q = ('q', False, True, "Q")
	r = ('r', False, True, "R")
	s = ('s', False, True, "S")
	t = ('t', False, True, "T")
	u = ('u', False, True, "U")
	v = ('v', False, True, "V")
	w = ('w', False, True, "W")
	x = ('x', False, True, "X")
	y = ('y', False, True, "Y")
	z = ('z', False, True, "Z")
	ZERO = ('0', False, True, "Zero")
	ONE = ('1', False, True, "1")
	TWO = ('2', False, True, "2")
	THREE = ('3', False, True, "3")
	FOUR = ('4', False, True, "4")
	FIVE = ('5', False, True, "5")
	SIX = ('6', False, True, "6")
	SEVEN = ('7', False, True, "7")
	EIGHT = ('8', False, True, "8")
	NINE = ('9', False, True, "9")
	Comma = (',', False, True, "Comma")
	Period = ('.', False, True, "Period")
	Semicolon = (';', False, True, "Semicolon")
	Minus = ('-', False, True, "-")
	Equal = ('=', False, True, "=")
	LBrack = ('[', False, True, "[")
	RBrack = (']', False, True, "]")
	FSlash = ('\\', False, True, "\\")

	LMB = (Button.left, True, False, "LMB")
	RMB = (Button.right, True, False, "RMB")
	MB4 = (Button.four, True, False, "MB4")
	MB5 = (Button.five, True, False, "MB5")

	LAlt = (Key.alt_l, True, True, "LAlt")
	CapsLock = (Key.caps_lock, True, True, "CapsLock")
	LCtrl = (Key.ctrl_l, True, True, "LCtrl")
	LShift = (Key.shift_l, True, True, "LShift")
	Space = (Key.space, True, True, "Space")
	Tab = (Key.tab, True, True, "Tab")
	F1 = (Key.f1, True, True, "F1")
	F2 = (Key.f2, True, True, "F2")
	F3 = (Key.f3, True, True, "F3")
	F4 = (Key.f4, True, True, "F4")
	F5 = (Key.f5, True, True, "F5")
	F6 = (Key.f6, True, True, "F6")
	F7 = (Key.f7, True, True, "F7")
	F8 = (Key.f8, True, True, "F8")
	F9 = (Key.f9, True, True, "F9")
	
